doctrine_migrations:
  all_or_nothing: true
  check_database_platform: true
  connection: default
  custom_template: null
  em: null
  enable_profiler: false
  factories: []
  migrations: []
  migrations_paths:
    - '%kernel.project_dir%/src/Migrations'
  organize_migrations: true
  services: []
  storage:
    table_storage:
      connection: default
      table_name: migration_versions