version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - webserver
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=events_myuzinc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=events@Myuzinc#2023
      - MYSQL_ROOT_PASSWORD=events@Myuzinc#2023
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  webserver:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
volumes:
  db_data:
